#!/bin/bash
set -euo pipefail

mkdir -p /workspace/output

python3 - <<'PY'
import json
from pathlib import Path

BREAK_POINTS = [
    {"set": 1, "medvedev_games": 1, "de_minaur_games": 1, "medvedev_points": "30", "de_minaur_points": "40", "server": "Daniil Medvedev", "opportunity": 1, "first_serve_in": True, "outcome": "saved", "serve_direction": "down_the_t", "rally_shots": 7, "terminal_player": "Alex De Minaur", "terminal_stroke": "backhand_lob", "terminal_court_position": "baseline", "terminal_result": "forced_error", "terminal_error": "deep"},
    {"set": 1, "medvedev_games": 2, "de_minaur_games": 2, "medvedev_points": "30", "de_minaur_points": "40", "server": "Daniil Medvedev", "opportunity": 1, "first_serve_in": True, "outcome": "converted", "serve_direction": "wide", "rally_shots": 4, "terminal_player": "Alex De Minaur", "terminal_stroke": "backhand_groundstroke", "terminal_court_position": "net", "terminal_result": "winner", "terminal_error": "none"},
    {"set": 1, "medvedev_games": 2, "de_minaur_games": 4, "medvedev_points": "15", "de_minaur_points": "40", "server": "Daniil Medvedev", "opportunity": 1, "first_serve_in": True, "outcome": "converted", "serve_direction": "down_the_t", "rally_shots": 2, "terminal_player": "Daniil Medvedev", "terminal_stroke": "forehand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "forced_error", "terminal_error": "net"},
    {"set": 2, "medvedev_games": 2, "de_minaur_games": 1, "medvedev_points": "40", "de_minaur_points": "15", "server": "Alex De Minaur", "opportunity": 1, "first_serve_in": False, "outcome": "saved", "serve_direction": "body", "rally_shots": 9, "terminal_player": "Daniil Medvedev", "terminal_stroke": "backhand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "unforced_error", "terminal_error": "net"},
    {"set": 2, "medvedev_games": 2, "de_minaur_games": 1, "medvedev_points": "40", "de_minaur_points": "30", "server": "Alex De Minaur", "opportunity": 2, "first_serve_in": True, "outcome": "saved", "serve_direction": "wide", "rally_shots": 3, "terminal_player": "Alex De Minaur", "terminal_stroke": "forehand_volley", "terminal_court_position": "net", "terminal_result": "winner", "terminal_error": "none"},
    {"set": 2, "medvedev_games": 2, "de_minaur_games": 1, "medvedev_points": "AD", "de_minaur_points": "40", "server": "Alex De Minaur", "opportunity": 3, "first_serve_in": False, "outcome": "saved", "serve_direction": "body", "rally_shots": 25, "terminal_player": "Alex De Minaur", "terminal_stroke": "forehand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "winner", "terminal_error": "none"},
    {"set": 2, "medvedev_games": 2, "de_minaur_games": 1, "medvedev_points": "AD", "de_minaur_points": "40", "server": "Alex De Minaur", "opportunity": 4, "first_serve_in": True, "outcome": "saved", "serve_direction": "body", "rally_shots": 1, "terminal_player": "Daniil Medvedev", "terminal_stroke": "backhand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "forced_error", "terminal_error": "deep"},
    {"set": 2, "medvedev_games": 2, "de_minaur_games": 1, "medvedev_points": "AD", "de_minaur_points": "40", "server": "Alex De Minaur", "opportunity": 5, "first_serve_in": True, "outcome": "saved", "serve_direction": "wide", "rally_shots": 1, "terminal_player": "Alex De Minaur", "terminal_stroke": "serve", "terminal_court_position": "serve", "terminal_result": "ace", "terminal_error": "none"},
    {"set": 2, "medvedev_games": 5, "de_minaur_games": 4, "medvedev_points": "40", "de_minaur_points": "15", "server": "Alex De Minaur", "opportunity": 1, "first_serve_in": True, "outcome": "converted", "serve_direction": "body", "rally_shots": 6, "terminal_player": "Alex De Minaur", "terminal_stroke": "forehand_slice", "terminal_court_position": "baseline", "terminal_result": "forced_error", "terminal_error": "deep"},
    {"set": 3, "medvedev_games": 2, "de_minaur_games": 1, "medvedev_points": "AD", "de_minaur_points": "40", "server": "Alex De Minaur", "opportunity": 1, "first_serve_in": True, "outcome": "converted", "serve_direction": "wide", "rally_shots": 12, "terminal_player": "Alex De Minaur", "terminal_stroke": "backhand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "unforced_error", "terminal_error": "deep"},
    {"set": 3, "medvedev_games": 4, "de_minaur_games": 1, "medvedev_points": "40", "de_minaur_points": "30", "server": "Alex De Minaur", "opportunity": 1, "first_serve_in": False, "outcome": "converted", "serve_direction": "wide", "rally_shots": 2, "terminal_player": "Alex De Minaur", "terminal_stroke": "forehand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "unforced_error", "terminal_error": "deep"},
    {"set": 4, "medvedev_games": 0, "de_minaur_games": 1, "medvedev_points": "30", "de_minaur_points": "40", "server": "Daniil Medvedev", "opportunity": 1, "first_serve_in": True, "outcome": "saved", "serve_direction": "wide", "rally_shots": 11, "terminal_player": "Daniil Medvedev", "terminal_stroke": "backhand_groundstroke", "terminal_court_position": "net", "terminal_result": "winner", "terminal_error": "none"},
    {"set": 4, "medvedev_games": 1, "de_minaur_games": 1, "medvedev_points": "40", "de_minaur_points": "0", "server": "Alex De Minaur", "opportunity": 1, "first_serve_in": False, "outcome": "converted", "serve_direction": "body", "rally_shots": 6, "terminal_player": "Alex De Minaur", "terminal_stroke": "backhand_volley", "terminal_court_position": "net", "terminal_result": "unforced_error", "terminal_error": "net"},
    {"set": 4, "medvedev_games": 3, "de_minaur_games": 1, "medvedev_points": "40", "de_minaur_points": "0", "server": "Alex De Minaur", "opportunity": 1, "first_serve_in": False, "outcome": "converted", "serve_direction": "body", "rally_shots": 8, "terminal_player": "Daniil Medvedev", "terminal_stroke": "backhand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "winner", "terminal_error": "none"},
    {"set": 4, "medvedev_games": 4, "de_minaur_games": 1, "medvedev_points": "30", "de_minaur_points": "40", "server": "Daniil Medvedev", "opportunity": 1, "first_serve_in": True, "outcome": "saved", "serve_direction": "down_the_t", "rally_shots": 1, "terminal_player": "Daniil Medvedev", "terminal_stroke": "serve", "terminal_court_position": "serve", "terminal_result": "unreturnable", "terminal_error": "none"},
    {"set": 4, "medvedev_games": 4, "de_minaur_games": 1, "medvedev_points": "AD", "de_minaur_points": "40", "server": "Daniil Medvedev", "opportunity": 2, "first_serve_in": False, "outcome": "saved", "serve_direction": "body", "rally_shots": 5, "terminal_player": "Alex De Minaur", "terminal_stroke": "backhand_groundstroke", "terminal_court_position": "baseline", "terminal_result": "unforced_error", "terminal_error": "deep"},
]

Path("/workspace/output/solution.json").write_text(json.dumps({"break_points": BREAK_POINTS}, indent=2))
PY
